services:
  mongodb:
    build: ./mongodb
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

  api:
    build: ./api
    env_file: .env
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

volumes:
  mongodb_volume:
